// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/muxi-Infra/autossl-qiniuyun/cron"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	qiniuSSL, err := cron.NewQiniuSSL()
	if err != nil {
		return nil, err
	}
	corn, err := cron.NewCorn(qiniuSSL)
	if err != nil {
		return nil, err
	}
	app, err := NewApp(corn)
	if err != nil {
		return nil, err
	}
	return app, nil
}

// wire.go:

// wireSet 定义所有依赖
var wireSet = wire.NewSet(cron.NewQiniuSSL, cron.NewCorn, NewApp)
